version: 2.1

orbs:
  android: circleci/android@2.1.2
  gcp-cli: circleci/gcp-cli@2.4.1

executors:
  android-executor:
    docker:
      - image: cimg/openjdk:21.0.2
      - image: circleci/android:api-30
    working_directory: ~/code
    environment:
      ADB_INSTALL_TIMEOUT: 5
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m -Dkotlin.incremental=false'
      ANDROID_HOME: /opt/android/sdk
      PATH: /opt/android/sdk/platform-tools:/opt/android/sdk/tools:$PATH

jobs:
  unit-test:
    executor: android-executor
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug
      - android/save-gradle-cache

workflows:
  test-and-build:
    jobs:
      - unit-test
