jobs:
    unit-test:
      executor:
        name: android/android-docker
        tag: 2022.08.1
      steps:
        - checkout
        - android/restore-gradle-cache
        - android/run-tests:
            test-command: ./gradlew testDebug
        - android/save-gradle-cache

workflows:
    version: 2
    build_and_test:
        jobs:
        - unit-test