version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/code
    environment:
      ADB_INSTALL_TIMEOUT: 5
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m -Dkotlin.incremental=false'

jobs:
  build:
    executor: android
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gradle-{{ checksum "build.gradle" }}
          - gradle-{{ checksum "app/build.gradle" }}
          - gradle-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs

  test:
    executor: android
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-{{ checksum "app/build.gradle" }}
            - gradle-

      - run:
          name: Start Emulator
          command: sdkmanager --install "system-images;android-30;google_apis;x86"

      - run:
          name: Create AVD
          command: echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" -d "pixel_8"

      - run:
          name: Launch Emulator
          command: emulator-headless -avd test -no-window -no-audio -gpu swiftshader &

      - run:
          name: Wait for Emulator
          command: |
            # wait for emulator to start
            circle-android wait-for-boot

      - run:
          name: Unlock Emulator
          command: adb shell input keyevent 82

      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest

      - store_test_results:
          path: app/build/reports/androidTests/connected

      - store_artifacts:
          path: app/build/reports/androidTests/connected

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
