version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: ./gradlew build
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      - android/run-tests:
          test-command: ./gradlew assembleRelease
      - android/run-tests:
          test-command: ./gradlew test

workflows:
  test:
    jobs:
      - test