version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      #- android/start-emulator-and-run-tests:
       #   test-command: ./gradlew connectedDebugAndroidTest
        #  system-image: system-image;android-29,google_apis;x86

workflows:
  test:
    jobs:
      - test